import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import PromoMarquee from "./components/PromoMarquee";
import FooterSection from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`} style={{
          background: "linear-gradient(160deg, #0D0D1A, #1B1B31, #251F40, #361A67, #412178)"
        }}
      >
        <PromoMarquee></PromoMarquee>
        <nav className="max-w-11/12 mx-auto">
          <Navbar></Navbar>
        </nav>
        <main>
          {children}
        </main>
        <footer>
          <FooterSection></FooterSection>
        </footer>
      </body>
    </html>
  );
}
